-- x_reposts プロジェクト用：リポスト履歴テーブル
create table trn_xrepost_logs (
    id bigint generated by default as identity primary key,
    target_user_id text not null,         -- リポスト対象ユーザーID
    reposted_by_user_id text not null,    -- BotユーザーID
    last_reposted_id text,                -- 最後にリポストしたツイートID
    created_at timestamp with time zone default now()
);

-- x_reposts プロジェクト用：ユーザーIDキャッシュ
create table trn_xrepost_user_cache (
    id bigint generated by default as identity primary key,
    username text not null unique,      -- ユーザー名
    user_id text not null,              -- X API のユーザーID
    created_at timestamp with time zone default now()
);
